name: Deploy

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

jobs:
  deploy-pypi:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
        with:
          python-version: "3.10"
          venv-id: "deploy"
          uv-dependency-install-flags: "--all-extras"
      - name: Run tests
        run: |
          uv run pytest
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"
        run: |
          uv build
          uv publish --token $PYPI_TOKEN
